# Generated by Django 4.1.2 on 2022-10-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crazy_book_club_app', '0002_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Reviews'},
        ),
    ]
